### PR TITLE
Cross target .NETSTANDARD 2.0

### PR DESCRIPTION
**Pull request by iamcarbon**
Cross target .NETSTANDARD2.0 to eliminate dependencies on modern runtimes including .NETCOREAPP2.0.

### CODE REVIEW

**Comment by jakubmisek** [comment]
`netstandard1.0` is compatible with `netstandard2.0`, is this necessary? This change causes two identical DLL files to be built, doubles the time needed to compile the project and makes resulting nuget package bigger.

**Comment by iamcarbon** [comment]
@jakubmisek  -- The .NETSTANDARD 2.0 target prevents modern frameworks including Mono 5.4, .NETCOREAPP2.0, .NET 4.7.1 & .NET 4.7.2 from pulling in 50+ additional libraries / facades.

When targeting .NETSTANDARD 2.0, everything is complied against a single facade (netstandard.dll) built directly into these modern frameworks. It also enables you to deploy to NET461 with a single netstandard.dll (vs the 50+ additional facades when things were broken out).

**Comment by iamcarbon** [comment]
Quick ping on this. There's an effort across the .NET ecosystem to eliminate these legacy facades from 1.x from being imported.

https://twitter.com/davidfowl/status/1018750315758116864

**Comment by jakubmisek** [comment]
@iamcarbon makes sense, thanks!

**Pull request merged**
